language: python
python:
  - "2.7"

# Cache PlatformIO packages using Travis CI container-based infrastructure
sudo: false
cache:
  directories:
    - "~/.platformio"

install:
  - pip install -U platformio
  - platformio update
  - platformio lib -g install 'ESP Async WebServer'

matrix:
  include:
    - env:
      - PLATFORMIO_CI_SRC=examples/esp8266_simple
      - PLATFORMIO_ADDITIONAL_ARGS='--lib="."'
      - BOARDS=--board=d1_mini
      - PLATFORMIO_CMD=ci
    - env:
      - PLATFORMIO_CI_SRC=examples/esp32_simple
      - PLATFORMIO_ADDITIONAL_ARGS='--lib=.'
      - BOARDS=--board=esp32doit-devkit-v1
      - PLATFORMIO_CMD=ci
    - env:
      - PLATFORMIO_CMD=test

script:
  - platformio ${PLATFORMIO_CMD} ${BOARDS} ${PLATFORMIO_ADDITIONAL_ARGS}